## user and car is connected to redis. but in none of these sir didn't write any code to
# # load the schema/db something because Redis doesn’t require any schema or initial data setup.
# #Redis data is created dynamically by the application, not preloaded
#  👉 Redis does NOT use schema at all
# So:
# No tables ❌
# No collections ❌
# No schema files ❌   
# 🔥 Why no schema in Redis?
# Because Redis is:
# Key → Value
# Example:
# SET cart:1001 "item1,item2"
# 👉 That’s it—no structure defined beforehand
# 🛒 What happens in cart service
# When app runs:
# User adds item
#         ↓
# Cart service writes to Redis
#         ↓
# Key is created automatically

# 👉 No need to pre-create anything

# 👤 What happens in user service
# User logs in
#         ↓
# Session stored in Redis

# 👉 Again:

# Key created dynamically (automatic ga values redis lo store aipothai. prestructer avasaram ledu)
# No schema needed

- name: configuring cart
  hosts: cart
  become: yes
  tasks:
   - name: enable node js 20
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: installing node js 20 
     ansible.builtin.dnf:
       name: nodejs
       state: present
    
   - name: creating system user roboshop
     ansible.builtin.user:
      name: roboshop
      state: present
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"
    
   - name: delete app directory   #if the directory is there it will delete otherwise keep quiet.
     ansible.builtin.file:
       path: /app
       state: absent

   - name: create a directory app
     ansible.builtin.file:
       path: /app
       state: directory

   - name: delete application code zip file  if anything exists
     ansible.builtin.file:
       path: /tmp/cart.zip
       state: absent
     
   - name: donloading application code 
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

   - name: unzip the application code
     ansible.builtin.unarchive:
       src: /tmp/cart.zip
       dest: /app
       remote_src: yes

   - name: install npm dependencies
     community.general.npm:
       path: /app

   - name: copying cart.service
     ansible.builtin.template:
      src: cart.service.j2
      dest: /etc/systemd/system/cart.service
      
   - name: start the cart
     ansible.builtin.service:
       name: cart
       state: started
       
