- name: create ec2 instace and route53 records
  hosts: local
  connection: local
  vars:
    sg_id: sg-014926186e33ca60e
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
    - mongodb
    - catalogue
    domain_name: devops88s.fun
    state: create



  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
       instance_type: "t3.micro"
       security_group: "{{sg_id}}"
       image_id: "{{ami_id}}"
       name: "{{item}}-{{env}}"   #mongodb-dev
       tags: 
         Project: roboshop
         Component: "{{item}}"
         Environment: "{{env}}"
         Name: "{{item}}-{{env}}"  
     loop: "{{instances}}"
     when: state =="create"
     register: ec2_output

   - name: prinitng the ec2_output
     ansible.builtin.debug : 
       msg: "{{ec2_output}}"
     when: state == "create"

   - name: creating the route53 records
     amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{item.item}}-{{env}}.{{domain_name}}"             #mongodb-dev.devops88s.fun, catalog-dev.devops88s.fun
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
     loop: "{{ec2_output.results}}"
     when: 
      -state == "create"
      -item.item != "fronted"

   - name: creating the route53 record for frontedn
     amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "roboshop-{{env}}.{{domain_name}}"             #roboshop-dev.devops88s.fun, generally for fronted we give public ip address right in revrse proxy
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
     loop: "{{ec2_output.results}}"
     when: 
      - item.item == "frontend" 
      - state == "create"

   - name: deleting route53 records
     amazon.aws.route53:
       state: absent
       zone: "{{domain_name}}"
       record: "{{item}}-{{env}}.{{domain_name}}"             #mongodb-dev.devops88s.fun, catalog-dev.devops88s.fun
       type: A
       ttl: 1
     loop: "{{instances}}"
     when: state == "destroy"

   - name: deleting ec2 instances 
     amazon.aws.ec2_instance:
      state: absent
      name: "{{item}}-{{env}}" 
     loop: "{{instances}}"
     when: state == "destroy" 
          




   



   
    
