# user (mongodb + redis) and car is connected to redis. but in none of these sir didn't write any code to
# # load the schema/db something because cart and user doesn't require any initial data setup.
# #Redis data is created dynamically by the application, not preloaded
# .sql / .js -->	preload required
# No DB scripts -->	runtime data
# as we know mongodb dbs collections document and in sql db tables rows next in rdis how data is?
#  👉 Redis does NOT use schema at all like sql
# So:
# No tables ❌
# No collections ❌
# No schema files ❌   
# 🔥 Why no schema in Redis?
# Because Redis is:
# Key → Value
# Example:
# SET cart:1001 "item1,item2"
# 👉 That’s it—no structure defined beforehand
# 🛒 What happens in cart service
# When app runs:
# User adds item
#         ↓
# Cart service writes to Redis
#         ↓
# Key is created automatically

# 👉 No need to pre-create anything

# 👤 What happens in user service
# User logs in
#         ↓
# Session stored in Redis

# 👉 Again:

# Key created dynamically (automatic ga values redis lo store aipothai. prestructer avasaram ledu)
# No schema needed

# User mongodb ki connect avuthundi mari data preload cheyyala vaddha?
# 🧠 Why catalogue why they loaded the data?
# Because:
# Product data must exist before app starts
# So they manually loaded it trhough script
#in real time how do they know preolaod reqeuired or not
# 👉 In real projects, they don’t “guess”
# They know by looking at requirements + application behavior + documentation
# Check project artifacts (what you did 👍)
# Engineers check repo:
# .sql / .js -->	preload required
# No DB scripts -->	runtime data
#user and cart application code lo .sql or .js script levu so no data preload is required for these two services
#and user account creation times aa details runtime lo mongodb and redis ki vellipothai(connection details and yela velthai anedi server.js lo vundi app code lo)

- name: configuring user
  hosts: user
  become: yes
  tasks:
   - name: enable node js 20
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: installing node js 20 
     ansible.builtin.dnf:
       name: nodejs
       state: present
    
   - name: creating system user roboshop
     ansible.builtin.user:
      name: roboshop
      state: present
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"
    
   - name: delete app directory   #if the directory is there it will delete otherwise keep quiet.
     ansible.builtin.file:
       path: /app
       state: absent

   - name: create a directory app
     ansible.builtin.file:
       path: /app
       state: directory

   - name: delete application code zip file  if anything exists
     ansible.builtin.file:
       path: /tmp/user.zip
       state: absent
     
   - name: donloading application code 
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

   - name: unzip the application code
     ansible.builtin.unarchive:
       src: /tmp/user.zip
       dest: /app
       remote_src: yes

   - name: install npm dependencies
     community.general.npm:
       path: /app

   - name: copying user.service
     ansible.builtin.template:
      src: user.service.j2
      dest: /etc/systemd/system/user.service
      
   - name: start and enable user
     ansible.builtin.service:
       name: user
       state: started
       enabled: yes



   # - name: deamon -reload
   #    ansible.builtin.systemd_service:
   #    daemon_reload: true
      